### ISSUE TITLE
Add sorting and filtering features

### ISSUE THREAD

**Issue by yodkwtf** [yodkwtf/cinematica-mern#3]
- Add sorting, searching, and filtering features for all items
- Sorting can be by name, release year, runtime, rating, etc.
- Filtering can be by genre, release year, rating bars, etc.
- Search can be on keypress event

**Comment by IrfanSalim** [comment]
hey, I would like to take this up

**Comment by yodkwtf** [comment]
Go ahead please, let me know if you need any help. Check the readme to set up the project.

**Comment by yodkwtf** [comment]
Closing this as it was resolved by @IrfanSalim in the PR #4
